# Generated by Django 5.0.1 on 2024-02-01 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0008_alter_subject_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quiz',
            new_name='subject',
        ),
    ]
