# Generated by Django 5.0.1 on 2024-02-20 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0012_alter_quiz_groups_alter_quiz_no_permission_students'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-id']},
        ),
    ]
