# Generated by Django 5.0.1 on 2024-03-05 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0019_alter_result_random_quizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraskedanswer',
            name='chosen_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz_app.answer'),
        ),
    ]
