# Generated by Django 5.0.1 on 2024-01-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_remove_student_grade_group_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(max_length=255),
        ),
    ]
