# Generated by Django 5.0.1 on 2024-01-20 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0003_alter_grade_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['-id']},
        ),
    ]
