# Generated by Django 5.0.1 on 2024-01-22 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0005_alter_group_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-id']},
        ),
    ]
