# Generated by Django 5.0.1 on 2024-01-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0007_alter_student_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
    ]
