# Generated by Django 5.0.1 on 2024-01-22 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0008_typegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='type_group',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='student_app.typegroup'),
            preserve_default=False,
        ),
    ]
