# Generated by Django 5.0.1 on 2024-01-30 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0011_alter_group_type_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='student_app.grade'),
        ),
    ]
